### ISSUE TITLE
Runner\Database throws exception when performing queries that don't return results

### ISSUE THREAD

**Issue by dreams-money** [cesar-v/processes#1]
If you run a simple query like "drop table sometable", it throws:

```
Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[HY000]: General error'
```

[Likely cause](http://stackoverflow.com/questions/20315898/pdo-error-pdoexception-with-message-sqlstatehy000-general-error)

**Comment by cesar-v** [comment]
The error is with
